### ISSUE TITLE
Remove save edits button

### ISSUE THREAD

**Issue by edwardchalstrey1** [colouring-cities/colouring-britain#244]
Change it so that the tick buttons being clicked result in a saved edit for fields, so there is a single step rather than two

**Comment by matkoniecz** [comment]
this seems applicable in general, not only to London

**Comment by polly64** [comment]
@mdsimpson42 can you add to core code

**Comment by mdsimpson42** [comment]
I've just changed this so that you DO need to click "save edits" to save changes to a tick box, because the behaviour in the Community section was inconsistent and confusing. This also seems like a good thing to do to avoid edits being created from accidental clicks.

I'm closing this issue. If we want to change this behaviour (again) later, we can create a new issue for it.

**Comment by polly64** [comment]
ok thanks
