### ISSUE TITLE
Age & History: Remove field requirements for Demolished buildings

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#248]
EDITED

In the Age & History category, under 'Lifespan and site history', remove the requirement to fill in all fields before the record can be saved.

![image](https://github.com/colouring-cities/colouring-britain/assets/21125422/0962bb86-ef1f-4f51-8682-cf32409201b2)

**Comment by mdsimpson42** [comment]
We don't have a dynamics category any more, so I'm not sure which fields this refers to. I'm going to close this. (We can always create another issue if the fields are still not behaving correctly in the new category.)

**Comment by polly64** [comment]
@mdsimpson42 refers to the Lifespan section of age and history

**Comment by mdsimpson42** [comment]
Given that we have decided to make the source type a required field elsewhere in the application, do we want to keep that as required here and just make the "Roughly what percentage of this building was inside the current site boundary?" question optional?

- [ ] Make "what percentage of this building" question optional.
- [ ] Change source links to only accept URLs instead of free text.

**Comment by mdsimpson42** [comment]
Not a trivial fix. 

1. Removing the requirement for the "what percentage" question causes errors. 
2. URL validation doesn't appear to work automatically and will require additional work.

**Comment by polly64** [comment]
@mdsimpson42 ok thanks. can we merge with an issue that deals with lifespan/historical data and close
