### ISSUE TITLE
age error priority issue

### ISSUE THREAD

**Issue by polly64** [colouring-cities/colouring-britain#373]
Hi @mdsimpson42  all the construction dates are under completion dates can you address today thanks,

**Comment by mdsimpson42** [comment]
The building age fields are working as intended. I repurposed the existing data fields, so:
- 'Year of construction of main building' has become 'Year of construction completed (best estimate)' 
- 'Earliest possible start year' is now the 'Year construction started (best estimate)'

The order and wording of the new fields are what we agreed to on our Zoom call on Tuesday.

If this is not the intended behaviour, I need to know what is wrong and how it should work in order to fix it.

**Comment by polly64** [comment]
@mdsimpson42 . 

- [ ] 'the year of construction of main building' needs to be connected to 'Year construction started (best estimate)' as these both refer to the start dates
- [ ]  'the year of construction completed' should be blank and should also read 'Year construction completed' ie omit 'of'

**Comment by mdsimpson42** [comment]
Are we 100% certain about this?  This seemed like the most logical way to handle the existing data that we already have in the database.

If I swap the fields over, then the dates won't make sense with the data that we already have. i.e. in this example, the start date would be AFTER the end date:

![image](https://github.com/user-attachments/assets/8c9f6bd0-dd49-4eaa-8d35-a09fec3410a7)

The other option is to only keep the old 'Year of construction of main building' and rename it to 'Year construction started (best estimate)', then add a NEW field called 'Year construction completed', but then we're effectively throwing away the 'Earliest/latest possible start year'.

**Comment by polly64** [comment]
@mdsimpson42 @Kate.court can you just reverse what was done and then just add 'completion' date as the we need to correct asap, thanks. Happy to test on staging.
